POST http://localhost:8010/products
Content-Type: application/json

{
    "title": "Voltas 1.5 Ton 5 Star Inverter Split AC (Copper, 2021 185V ADJ, White)",
    "price": 39999,
    "description": "Split AC with inverter compressor: Variable speed compressor which adjusts power depending on heat load. It is most energy efficient and has lowest-noise operation",
    "imageUrl": "https://m.media-amazon.com/images/I/71XfQ5zXk8L._AC_UY218_.jpg",
    "category": {
      "name": "Electronics"
    }
}

###
