-- Create few sample products and categories
INSERT INTO category (name) VALUES ('Electronics');
INSERT INTO category (name) VALUES ('Books');
INSERT INTO category (name) VALUES ('Clothing');
INSERT INTO category (name) VALUES ('Home & Kitchen');

INSERT INTO product (title, price, category_id, description, image_url) VALUES ('Apple iPhone 11', 699, 1, 'Apple iPhone 11 is a great phone with a great camera', 'https://www.apple.com/newsroom/images/product/iphone/standard/Apple_announce-iphone11pro_091019_big.jpg.large.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('Samsung Galaxy S20', 799, 1, 'Samsung Galaxy S20 is a great phone with a great camera', 'https://www.samsung.com/us/smartphones/galaxy-s20-5g/_jcr_content/og/og_image.img.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('MacBook Pro', 1299, 1, 'MacBook Pro is a great laptop with a great camera', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-spacegray-select-202005?wid=892&hei=820&&qlt=80&.v=1587460554798');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('Dell XPS 13', 999, 1, 'Dell XPS 13 is a great laptop with a great camera', 'https://i.dell.com/is/image/DellContent//content/dam/global-site-design/product_images/dell_client_products/notebooks/xps_notebooks/13_9300/general/xps-13-9300-laptop-landing-hero-504x350-ng.psd?fmt=jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('The Alchemist', 10, 2, 'The Alchemist is a great book', 'https://images-na.ssl-images-amazon.com/images/I/51a5n6zXyzL._SX329_BO1,204,203,200_.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('The Da Vinci Code', 15, 2, 'The Da Vinci Code is a great book', 'https://images-na.ssl-images-amazon.com/images/I/51a5n6zXyzL._SX329_BO1,204,203,200_.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('The Monk Who Sold His Ferrari', 20, 2, 'The Monk Who Sold His Ferrari is a great book', 'https://images-na.ssl-images-amazon.com/images/I/51a5n6zXyzL._SX329_BO1,204,203,200_.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('The 5 AM Club', 25, 2, 'The 5 AM Club is a great book', 'https://images-na.ssl-images-amazon.com/images/I/51a5n6zXyzL._SX329_BO1,204,203,200_.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('Nike Air Max', 100, 3, 'Nike Air Max is a great shoe', 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/5e6f3b3e-3e3e-4e3e-8e3e-3e3e3e3e3e3e/air-max-270-react-shoe-5X5zZG.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('Adidas Superstar', 80, 3, 'Adidas Superstar is a great shoe', 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/5e6f3b3e-3e3e-4e3e-8e3e-3e3e3e3e3e3e/air-max-270-react-shoe-5X5zZG.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('Puma RS-X', 90, 3, 'Puma RS-X is a great shoe', 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/5e6f3b3e-3e3e-4e3e-8e3e-3e3e3e3e3e3e/air-max-270-react-shoe-5X5zZG.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('Reebok Classic', 70, 3, 'Reebok Classic is a great shoe', 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/5e6f3b3e-3e3e-4e3e-8e3e-3e3e3e3e3e3e/air-max-270-react-shoe-5X5zZG.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('KitchenAid Stand Mixer', 300, 4, 'KitchenAid Stand Mixer is a great mixer', 'https://www.kitchenaid.com/content/dam/global/kitchenaid/countertop-appliances/stand-mixers/hero/hero-ksm150ps-1560x878.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('Instant Pot', 100, 4, 'Instant Pot is a great pot', 'https://www.kitchenaid.com/content/dam/global/kitchenaid/countertop-appliances/stand-mixers/hero/hero-ksm150ps-1560x878.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('Cuisinart Food Processor', 150, 4, 'Cuisinart Food Processor is a great processor', 'https://www.kitchenaid.com/content/dam/global/kitchenaid/countertop-appliances/stand-mixers/hero/hero-ksm150ps-1560x878.jpg');
INSERT INTO product (title, price, category_id, description, image_url) VALUES ('Ninja Blender', 200, 4, 'Ninja Blender is a great blender', 'https://www.kitchenaid.com/content/dam/global/kitchenaid/countertop-appliances/stand-mixers/hero/hero-ksm150ps-1560x878.jpg');
